ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  enabled: true
  hostname: grafana.example.com
  path: /
  pathType: ImplementationSpecific
  secrets:
  - hosts:
    - grafana.example.com
    name: grafana-tls
  tls: true
