# Basic cert-manager values.yaml for Helm installation

# Enable installation of Custom Resource Definitions (CRDs)
installCRDs: true

# Set the cert-manager controller replica count directly
replicaCount: 1

# cert-manager webhook configuration
webhook:
  replicaCount: 1

# cert-manager CA Injector configuration
cainjector:
  replicaCount: 1
