# values.yaml

# Enable Grafana
grafana:
  enabled: true
  # Force deploy dashboards even if Grafana is enabled
  forceDeployDashboards: true
  # Enable Grafana Ingress
  ingress:
    enabled: true
    # Set your domain here
    hosts:
      - grafana.example.com

# Enable Prometheus metrics collection
prometheus:
  enabled: true

# Enable node metrics collection via Node Exporter
nodeExporter:
  enabled: true

# Disable unnecessary components for a minimal setup
alertmanager:
  enabled: false

# Ensure Prometheus scrapes node metrics
prometheusOperator:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: true
    serviceMonitorNamespaceSelectorNilUsesHelmValues: true

# Minimal Kubernetes service monitors for core components
kubelet:
  serviceMonitor:
    enabled: true