# -------------------------------------------------------------------
# Chart-managed CRDs + Operator
# -------------------------------------------------------------------
crds:
  install: true

opentelemetry-operator:
  enabled: true
  admissionWebhooks:
    failurePolicy: Ignore

# -------------------------------------------------------------------
# Don’t generate the default “collector” CR
# -------------------------------------------------------------------
defaultCRConfig:
  enabled: false

# -------------------------------------------------------------------
# Define exactly one additional collector: “central”
# (daemon & cluster use the chart’s built-in defaults, enabled=true)
# -------------------------------------------------------------------
collectors:
  central:
    enabled: true
    suffix: central
    mode: deployment
    replicas: 2

    resources:
      requests:
        cpu:    200m
        memory: 300Mi
      limits:
        cpu:    400m
        memory: 600Mi

    config:
      receivers:
        loki:
          protocols:
            http:
              endpoint: 0.0.0.0:3500
            grpc:
              endpoint: 0.0.0.0:3600
          useIncomingTimestamp: true

      processors:
        batch: {}

      exporters:
        otlp:
          endpoint: central-collector.opentelemetry.svc.cluster.local:4317

      service:
        pipelines:
          logs:
            receivers:  [loki]
            processors: [batch]
            exporters:  [otlp]
