image:
  repository: louislam/uptime-kuma
  pullPolicy: IfNotPresent
  tag: "1.23.13-debian"

volume:
  enabled: true
  accessMode: ReadWriteOnce
  size: 4Gi

service:
  type: ClusterIP
  port: 3001

ingress:
  enabled: false

mariadb:
  enabled: false

resources: {}