# Minimal values.yaml for Grafana with TLS Ingress and Persistent Storage

## Ingress configuration
ingress:
  enabled: true
  hostname: demo-grafana.ankra.dev
  tls: true
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Adjust if using a different ingress controller
  secrets: []  # Assumes TLS secret exists as <hostname>-tls

## Persistence configuration
persistence:
  enabled: true
  size: 10Gi  # Adjust storage size as needed

## Base image configuration (optional override)
image:
  repository: bitnami/grafana
  tag: 12.0.1-debian-12-r3