# 1. Install CRDs as part of the release
crds:
  enabled: true
  keep: true

# 2. Core cert-manager settings (you can leave most at their defaults)
installCRDs: false      # deprecated alias; prefer crds.enabled
global:
  logLevel: 2

replicaCount: 2
webhook:
  replicaCount: 2
cainjector:
  replicaCount: 2

# 3. Inject both Issuer and ClusterIssuer
extraObjects:
  # a) Namespaced SelfSigned Issuer
  - |
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: {{ include "cert-manager.fullname" . }}-selfsigned-issuer
      namespace: {{ .Release.Namespace }}
    spec:
      selfSigned: {}

  # b) Cluster-wide SelfSigned ClusterIssuer
  - |
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: {{ include "cert-manager.fullname" . }}-selfsigned-clusterissuer
    spec:
      selfSigned: {}
